### ISSUE TITLE
Semaphore wait will block thread

### ISSUE THREAD

**Issue by fengqiangboy** [OmerMor/AsyncBridge#24]
When I use `Semaphore` in async function. It will block thread.

Is any way to implement `semaphore.waitAsync();` like `SemaphoreSlim` in .net framework 4

**Comment by jnm2** [comment]
@fengqiangboy Yes, one way is to copy the SemaphoreSlim class from later .NET versions and backport the code, or at least the parts of the SemaphoreSlim class that you need.

It's currently outside the scope of AsyncBridge to implement all .NET async APIs. This is not an absolute no, but someone would have to propose something less ambitious that follows a theme. ("I'm missing this API now, can you backport it to .NET 3.5" is not an appealing theme.)

And someone would have to be willing to invest the time. If there was a proposal that feels right for AsyncBridge, code contributions would be welcome.
